### ISSUE TITLE
Stuck on getting EventListener to work on more than one sqaure

### ISSUE THREAD

**Issue by natashagresh** [natashagresh/taylor_swift_concentration#3]
Hi. I am doing the concentration game and been stuck all afternoon as I have been unable to get more than one square to accept the eventlistener and to change colours. Sometimes that one square- always the first square on the top left, doesn't work either. Im not sure if it is the clickCounter and shuffle that is messing everything up. Ive tried adding another function but this doesn't help. 
This action is from 63 to 72. 
Thanks.

**Comment by annarankin** [comment]
Hi Natasha! I see the last time you pushed was about 23 hours ago - have you made progress on this?

One thing I noticed in your code on line 72:

``` javascript
cards.addEventListener('click', clickSquares);
```

The variable `cards` is pointing to a single reference to the first of your divs with a class of `card`:

``` javascript
var cards=document.querySelector('.cards');
```

Make sure you catch when you're using `querySelector` vs. `querySelectorAll`!
