### ISSUE TITLE
getting card to stay faceup

### ISSUE THREAD

**Issue by natashagresh** [natashagresh/taylor_swift_concentration#4]
https://github.com/natashagresh/project_one_concentration

Hi,

I'm currently having an issue with getting my cards to stay up. Basically when I click a card, it shows me its image but it doesn't go facedown until i have clicked the same card or another card. It is not understanding my code of having two cards up at the same time, because just as I click the second card-the first one goes facedown again. 

here is my code for identifying a winner/loser=

``` javascript
var clickSquare = function(event){
    card = event.target;
    card.classList.remove("facedown");
  console.log(event.target)
  clickCounter++;
  if(clickCounter === 24) { 
    // var lost=document.createElement('H2');
    // var lost2=document.createTextNode('Sorry, you lost');
    // lost.appendChild(lost2);
    console.log('lost');
    //if matches aren't all complete game over
  } if (clickCounter === 1){
    clickCounter++;
  } else if (clickCounter % 2 === 0) {
    //matching check logic
    //previous card matches this card??
    var imageClasses = ['image1', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7', 'image8'];
    var cardImageClass = imageClasses.filter(function(className){
      return card.classList.contains(className);
    });

    var previousCardImageClass = imageClasses.filter(function(className){
      return previousCard.classList.contains(className);
    });
    if (previousCardImageClass !== cardImageClass) {
      // If they don't match, then flip facedown again
        card.classList.add('facedown');
        previousCard.classList.add('facedown');
        window.setTimeout(clickSquare, 2000);
    }
  }
  previousCard = card;
};

Thank you! 
```

**Comment by annarankin** [comment]
Hi Natasha! How's this going? Have you tried console.logging `clickCounter` every time a card is clicked to see what the number is?

**Comment by natashagresh** [comment]
Hi, yes I have. It recognises the clickcounts so my 4th click is giving me back 4 etc. the issue now is getting two matching ones to stay up and spend all afternoon trying to play with my code, but haven't figured it out yet. Please help! 

Below is my code to try and recognise two matching cards and keep them faceup. 

``` javascript
var previousCard;
var clickSquare = function(event){
    card = event.target;
    card.classList.remove('facedown');
  console.log(event.target);
  clickCounter++;
  if(clickCounter === 26) { 
    // var lost=document.createElement('h2');
    // var lost2=document.createTextNode('Sorry, you lost');
    // lost.appendChild(lost2);
    console.log('lost');
    //if matches aren't all complete game over
  } else if (clickCounter % 2=== 1){
    previousCard = card;
  } else if (clickCounter % 2 === 0) { 
    console.log('blah');
    //matching check logic
    //previous card matches this card??
    var imageClasses = ['image1', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7', 'image8'];
    var cardImageClass = imageClasses.filter(function(className){
      return card.classList.contains(className);
    });

    var previousCardImageClass = imageClasses.filter(function(className){
      return previousCard.classList.contains(className);
    });
    if(previousCardImageClass === cardImageClass){
      card.classList.remove('facedown');
      previousCard.classList.remove('facedown');
      console.log('meh');
     } else if (previousCardImageClass !== cardImageClass) {
      // If they don't match, then flip facedown again
        window.setTimeout(function() {
          card.classList.add('facedown');
          previousCard.classList.add('facedown');
        }, 1000);   
    }
  }
};
```

**Comment by annarankin** [comment]
Hey Natasha, your code seems to be working except for one thing - try console.logging your `previousCardImageClass` and `cardImageClass` variables and seeing what the data types are.

**Comment by natashagresh** [comment]
It says undefined and if I look at the issue it opens the VM49x in the console, which i just don't understand!

**Comment by annarankin** [comment]
Hey Natasha, I mean from within your function - try adding console logs after you define the variables in your code, then reload your page and try clicking around. Ex:

``` javascript
...
    var cardImageClass = imageClasses.filter(function(className){
      return card.classList.contains(className);
    });

    var previousCardImageClass = imageClasses.filter(function(className){
      return previousCard.classList.contains(className);
    });
// Added console logs
    console.log(previousCardImageClass);
    console.log(cardImageClass);
    if(previousCardImageClass === cardImageClass){
...
```

**Comment by natashagresh** [comment]
Hi, when I put the console.log(previousCardImageClass) and console.log (cardImageClass) it usually returns the image number e.g ['image2'] except in the first if statement in the below code ( if(previousCardImageClass === cardImageClass)). For some reason, it is not picking up this code. However, i feel like it is vital because even though i now it is redundant-with the following if else statement (else if (previousCardImageClass !== cardImageClass)), when i remove it, it still doesn't work. Technically i feel like it should work with only the second if else code.

**Comment by natashagresh** [comment]
opps sorry, forgot to include code. silly me! ive now taken out the first if statement and added an else at the end with a console.log but still not picking it up. this means that it the function isnt going further than picking up two unmatched cards.     

var clickSquare = function(event){
    card = event.target;
    card.classList.remove('facedown');
  console.log(event.target);
  clickCounter++;
  if(clickCounter === 26) { 
    // var lost=document.createElement('h2');
    // lost.textContent('Sorry, we are never ever getting back together');
    // var lost2=document.createTextNode('Sorry, you lost');
    // lost.appendChild(lost2);
    console.log('lost');
    //if matches aren't all complete game over
  } else if (clickCounter % 2=== 1){
    previousCard = card;
  } else if (clickCounter % 2 === 0) { 
    console.log('blah');
    //matching check logic
    //previous card matches this card??
    var imageClasses = ['image1', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7', 'image8'];
    var cardImageClass = imageClasses.filter(function(className){
      return card.classList.contains(className);
    });

```
var previousCardImageClass = imageClasses.filter(function(className){
  return previousCard.classList.contains(className);
});

console.log(previousCardImageClass);
console.log(cardImageClass);

// if(previousCardImageClass === cardImageClass){
//   card.classList.remove('facedown');
//   previousCard.classList.remove('facedown');
//   console.log('meh');
//  } else 
if (previousCardImageClass !== cardImageClass) {
  // If they don't match, then flip facedown again
    window.setTimeout(function() {
      card.classList.add('facedown');
      previousCard.classList.add('facedown');
    }, 1000);   
    console.log(previousCardImageClass);
    console.log(cardImageClass);
} 
 else {
  console.log('meh');
}
```

  }
};
